### ISSUE TITLE
Support canceling requests of skipped pages

### ISSUE THREAD

**Issue by rocwang** [rocwang/vue-virtual-scroll-grid#133]
When a user scroll the list really quickly, this component should skip loading the intermediate pages from server to improve performance.

**Comment by BryceBarbara** [comment]
This would be very helpful. I just got a good way through an implementation of something using this and realized this isn't gonna work for our needs without that. 🤦‍♂️ 

That'll show me for not going through _all_ the issues of any third-party component I might need to use.
