### ISSUE TITLE
[FEATURE REQUEST] Support horizontal scroll

### ISSUE THREAD

**Issue by mesqueeb** [rocwang/vue-virtual-scroll-grid#141]
I have a use case where I need a long list of names that's horizontally scrollable. I'd love to be able to use this library as well. : )

In my use case, the list is pre-fetched, so I would only need the render optimisations, not the "getPage" async method for retrieving more results.

**Comment by rocwang** [comment]
Decided not to support horizontal scroll. Want to keep the library simple for now.

**Comment by zumm** [comment]
Any chance you may change your mind? I need horizontal scroll for mobile version of my app.

**Comment by rocwang** [comment]
Unfortunately, I don't have any capacity to add this feature at the moment.

**Comment by zumm** [comment]
@rocwang Can i help mb? I forked your repo and implemented this feature. I use `grid-auto-flow` css property to infer scroll mode. There is no backward compatibility breaking. Should i make a pull request? I can also adapt tests and demo.

**Comment by rocwang** [comment]
@zumm Yes, a PR is definitely welcomed.
