### ISSUE TITLE
[BUG] some type errors in pipeline.ts

### ISSUE THREAD

**Issue by mesqueeb** [rocwang/vue-virtual-scroll-grid#154]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/3253920/142576725-641de698-4468-4fed-bf5a-1eb6350bf7e7.png">

**Comment by mesqueeb** [comment]
causes: 
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/3253920/142576781-3160c3be-fdb2-407a-af74-4a58b280c098.png">


PS: I don't know why our Webpack is trying to read your TS file... that's probably an issue on our end. But the fact that the type errors are there might be able to be fixed in your source code.

**Comment by rocwang** [comment]
I've fixed the type issue in `v1.2.3`. It looks like have something to do with TypeScript 4.5.

With that said, ideally, the library's type issue shouldn't be your project concern to begin with.  If you use `vue-tsc` to check the types, there is a "--skipLibCheck" option you can set to skip type checking on libraries.
