### ISSUE TITLE
[BUG] Argument of type 'Ref<HTMLElement | SVGElement | VueInstance | undefined>' is not assignable to parameter of type 'MaybeElementRef'.

### ISSUE THREAD

**Issue by mesqueeb** [rocwang/vue-virtual-scroll-grid#164]
Recently I'm getting issues like these again in my typescript based project

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/3253920/146860287-eacd83d5-fd8b-4a68-91e3-99601c51194c.png">

I do have `skipLibCheck: true` in tsconfig, so not sure what's causing it though : S
```
ERROR in ../../node_modules/vue-virtual-scroll-grid/src/Grid.vue:97:37
TS2345: Argument of type 'Ref<HTMLElement | SVGElement | VueInstance | undefined>' is not assignable to parameter of type 'MaybeElementRef'.
  Property '[RefSymbol]' is missing in type 'Ref<HTMLElement | SVGElement | VueInstance | undefined>' but required in type 'Ref<HTMLElement | SVGElement | VueInstance | null | undefined>'.
     95 |       pageSize$: fromProp(props, "pageSize"),
     96 |       // a stream of item size measurements when it is changed
  >  97 |       itemRect$: fromResizeObserver(probeRef, "contentRect"),
        |                                     ^^^^^^^^
     98 |       // a stream of root elements when it is resized
     99 |       rootResize$: fromResizeObserver(rootRef, "target"),
    100 |       // a stream of root elements when scrolling

ERROR in ../../node_modules/vue-virtual-scroll-grid/src/Grid.vue:99:39
TS2345: Argument of type 'Ref<HTMLElement | SVGElement | VueInstance | undefined>' is not assignable to parameter of type 'MaybeElementRef'.
     97 |       itemRect$: fromResizeObserver(probeRef, "contentRect"),
     98 |       // a stream of root elements when it is resized
  >  99 |       rootResize$: fromResizeObserver(rootRef, "target"),
        |                                       ^^^^^^^
    100 |       // a stream of root elements when scrolling
    101 |       scroll$: fromWindowScroll(rootRef),
    102 |       scrollTo$: fromProp(props, "scrollTo"),

ERROR in ../../node_modules/vue-virtual-scroll-grid/src/Grid.vue:101:33
TS2345: Argument of type 'Ref<HTMLElement | SVGElement | VueInstance | undefined>' is not assignable to parameter of type 'MaybeElementRef'.
     99 |       rootResize$: fromResizeObserver(rootRef, "target"),
    100 |       // a stream of root elements when scrolling
  > 101 |       scroll$: fromWindowScroll(rootRef),
        |                                 ^^^^^^^
    102 |       scrollTo$: fromProp(props, "scrollTo"),
    103 |     });
    104 |
```

<img width="244" alt="image" src="https://user-images.githubusercontent.com/3253920/146860316-e92694e3-8097-4b48-afd5-5c6918fd0982.png">

**Comment by rocwang** [comment]
It looks like an easy issue to fix. However, I shouldn't have exposed internal types. I will look into this.

**Comment by mesqueeb** [comment]
@rocwang I checked the code, I think you should use this command to generate the proper types for your library:

`"gen:types": "vue-tsc --declaration --emitDeclarationOnly",`

in you tsconfig, set `"declaration": false,` instead of `true` and only create the declaration with vue-tsc.

For vue-tsc to work you need this instead of your `"declaration": true,`
```
"compilerOptions": {
    "outDir": "dist",
    "baseUrl": "."
  },
```

**Comment by mesqueeb** [comment]
@rocwang do you want me to make a PR or do you think you can fix it?
I need it today to be able to release our app :P  so I think I'll make a fork

**Comment by mesqueeb** [comment]
@rocwang just opened a PR with a potential fix. checking my branch now.

**Comment by mesqueeb** [comment]
@rocwang update: it doesn't fix the issue yet. hold on I'm trying some things on my fork

**Comment by mesqueeb** [comment]
@rocwang I was able to fix the issue but now seeing this issue
<img width="749" alt="image" src="https://user-images.githubusercontent.com/3253920/146876645-f930c4b9-c28c-4dec-91c9-9172ddd9a50c.png">

I'm gonna try and solve this by providing a named export instead. This will be a breaking change, but either way it might be a good idea to only stick to named exports anyway.

That way in the future you can provide other stuff as well in your exports like types and / or other helper components to the grid.

**Comment by mesqueeb** [comment]
@rocwang please ignore my last comment. I had something setup wrong on my end. I'm still testing my fork, please wait a few more min.

**Comment by mesqueeb** [comment]
Dear @rocwang this PR (#166) fixes this issue!

It's good to merge now!
thanks so much for your cooperation.
