### ISSUE TITLE
[FEATURE REQUEST] enhance `scrollTo` prop if put Grid in a `overflow: auto` element

### ISSUE THREAD

**Issue by hunterliu1003** [rocwang/vue-virtual-scroll-grid#182]
In my use case, I put a Grid component in a `overflow: auto` element, then the prop `scrollTo` not working

```html
<div style="height: 300px; overflow: auto">
  <Grid ... scrollTo="activeIndex">...</Grid>
</div>
```

I think the reason is the prop `scrollTo` is implemented with `window.scrollTo`.

[Grid.vue: L114-L120](https://github.com/rocwang/vue-virtual-scroll-grid/blob/5ee62b9b512e9ec811ee7eb51ae83442ebf21ddb/src/Grid.vue?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L114-L120)

```js
onUpdated(
  once(() => {
    windowScrollTo$.subscribe((next) => {
      window.scrollTo({ top: next, behavior: "smooth" });
    });
  })
);
```

Do you have any ideas or solutions to improve the `scrollTo` with my use case?

**Comment by rocwang** [comment]
I think it should be possible by replace `window` with the grid container.

**Comment by hunterliu1003** [comment]
Do you plan to add this functionality? 

Btw, I send you one time sponsorship for this great component and your hard work. Thanks

**Comment by rocwang** [comment]
I'll take a look this weekend. Thanks for the sponsorship! 👍

**Comment by rocwang** [comment]
@hunterliu1003 

This is supported in v1.4.0 now. Let me know if you have any problem with it.

**Comment by hunterliu1003** [comment]
@rocwang 

It just worked like a charm. Thank you for implementing this feature soooooo fast!
