### ISSUE TITLE
[BUG] `ResizeObserver loop completed with undelivered notifications` as window is resized, lags browser

### ISSUE THREAD

**Issue by grenappels** [rocwang/vue-virtual-scroll-grid#194]
**Describe the bug**
I'm getting a `ResizeObserver loop completed with undelivered notifications.` error every time the window is resized, and there seems to be a lag spike with each occurrence of this. I have tested on macOS Safari 15.1. If I try to recreate the behavior with a vanilla grid instead of using this component, the issue goes away.

**To Reproduce**
Fortunately the error occurs even on the demo app, so if you go to https://grid.kiwiberry.nz and look in the inspector you should see this error occurring every tick that the window is being resized.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.0.1
 - Browser: Safari 15.1

<img width="917" alt="Screen Shot 2022-03-30 at 9 46 24 AM" src="https://user-images.githubusercontent.com/18580013/160849567-8f014dea-3eef-4402-ab51-3c7e4617e859.png">

**Comment by rocwang** [comment]
Thanks for the bug report!. This is fixed in [`v1.4.2` ](https://www.npmjs.com/package/vue-virtual-scroll-grid/v/1.4.2).
