### ISSUE TITLE
[BUG] If pageProvider returns an array that is not the same length as pageSize, the page never loads

### ISSUE THREAD

**Issue by grenappels** [rocwang/vue-virtual-scroll-grid#197]
**Describe the bug**
See title

**To Reproduce**
I have reproduced the error in a fork of the live example here: https://codesandbox.io/s/vue-virtual-scroll-grid-esm-with-axios-forked-yx4565?file=/App.vue
What I changed was I set the grid length to 47, and page size to 10, and made it return an array that's only 7 long on the last page (as an API seems likely to do if the count of remaining items are less than the page size). The result is that the last 7 items stay as placeholders.

**Temporary solution!**
For now if you'd like to subvert this behavior you can just pad the pageProvider's returned array to be as long as the page size, like this:

`return Object.assign(new Array(pageSize), myArrayThatsTooSmall)`

The returned array will have `undefined` entries at the end but if your grid length matches the total count, it should be invisible to the user.

**Additional context**
I'm an experienced software dev but really new to Vue and webdev in general, so this might be my own error, or I might be using the wrong terms for things. I really love this library though! It's really great. Sorry to make two issues back-to-back 😅

**Comment by rocwang** [comment]
Thanks for the bug report!. This is fixed in [`v1.4.2` ](https://www.npmjs.com/package/vue-virtual-scroll-grid/v/1.4.2).
