### ISSUE TITLE
[BUG] Nodes states are shared between items

### ISSUE THREAD

**Issue by zumm** [rocwang/vue-virtual-scroll-grid#227]
Since component uses item indexes as keys, vue renders items with same nodes. It causes some side effects, e.g. nodes keep focus.

**Comment by rocwang** [comment]
If I recall correctly, I use `index` as the `key` of `v-for` for performance benefits, so Vue just patch changed nodes, and leave unchanged node untouched.

Could you elaborate on this issue? Ideally provide something that demonstrates the bug.

**Comment by zumm** [comment]
See this [demo](https://codesandbox.io/s/kind-mccarthy-csnrp4?file=/src/App.vue). Click on some item. It should become focused (red). Then just scroll and you should see other items focused.

I think using `internalItem.index` as key is better way. But even that is not enough since `pageProvider` may be changed. So also grid must provide option to allow user use part of item as key.

**Comment by zumm** [comment]
At other side supporting this option can be tricky because of items have loading time during which they are undefined. Mb generating GUIDs for items is the way.

**Comment by rocwang** [comment]
Hmm, this is interesting.

We can start with experimenting with random `key` on each item or using a hash of the item as `key`.
Not sure about the performance implication with this though.

**Comment by zumm** [comment]
Wanna me to implement that?

**Comment by rocwang** [comment]
@zumm You are more than welcome to fix it! If it's not urgent to you, you can leave it to me and I'll try to find sometime for it.

**Comment by shemsiu** [comment]
@rocwang would it be a solution to let the users define which field (from the list passed through `pageProvider`) that should be used as the `key` identifier on v-for?

**Comment by rocwang** [comment]
> would it be a solution to let the users define which field (from the list passed through pageProvider) that should be used as the key identifier on v-for?
> And if none defined then use a random key

#230 uses timestamp as the `v-for` key, which should fix the issue more or less. I'll punt "the solution to et the users define which field (from the list passed through pageProvider) that should be used as the key identifier on v-for" for now.
