### ISSUE TITLE
[BUG] Incorrect reaction to `pageProvider` change

### ISSUE THREAD

**Issue by zumm** [rocwang/vue-virtual-scroll-grid#228]
See [demo](https://codesandbox.io/s/laughing-meitner-i0ivfc?file=/src/App.vue). Try to select collection B without scrolling. New items will not be rendered.

I think it happens because `length` and `pageProvider` are changing at same time and pipeline can't handle it correctly.

**Comment by mesqueeb** [comment]
we've seen the same issue, let us know if we can help providing another reproduction

**Comment by rocwang** [comment]
Thanks for the bug report. I can confirm it from my side. Will get it fixed.

**Comment by rocwang** [comment]
This has been fixed in `v.1.7.1`.

I verified the fix by updating the provided demo with `"vue-virtual-scroll-grid": "1.7.1"`. See https://codesandbox.io/s/optimistic-bush-j77bjn?file=/package.json:239-273
