### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by c-peiron** [rocwang/vue-virtual-scroll-grid#263]
I am trying to use this component in my project but when I load it in my view I get the following error:

Module parse failed: Unexpected token (4836:58)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   let vertical;
|   let horizontal;
>   for (let parent = element; parent = parent.assignedSlot?.parentElement ?? parent.parentElement; ) {
|     const parentStyle = getComputedStyle(parent);
|     if (excludeStaticParent && parentStyle.position === "static")

Do you know what could it be due to?

**Comment by rocwang** [comment]
I have no clue given the limited information.

Would you be able to create a minimal replication of this issue as a git repo?

**Comment by c-peiron** [comment]
Hello and thank you for your reply.

The problem arises just after doing the npm install and the corresponding import in my component. Without even using it.

Sorry but I can't share the project.

Thank you.

**Comment by rocwang** [comment]
By "a minimal replication", I don't mean your current project, but a separated newly created repo that can replicate on this issue with the minimal code.

Or could you share more info on the issue, like:

1. A better formatted stack trace and error message. It looks like it was thrown by webpack.
2. Which node version are you using?
