### ISSUE TITLE
[FEATURE REQUEST] SSR support

### ISSUE THREAD

**Issue by dongnaebi** [rocwang/vue-virtual-scroll-grid#305]
**Is your feature request related to a problem? Please describe.**
using it in nuxt, got error: window is not defined

**Describe the solution you'd like**
in server side, prerender the first page

**Describe alternatives you've considered**
null

**Additional context**
null

**Comment by rocwang** [comment]
As the component is tightly coupled with DOM element geometry, I guess it won't be trivial to support SSR with dynamic number of rendered items.

I don't have any experience with SSR, but I think the component can just render a fixed number of items (or nothing at all), and let the frontend to handle the layout during hydration.

I am afraid I don't have the capacity to work on this at the moment. PR is welcomed as always.
