### ISSUE TITLE
Enhancement: Create 'scrollTo' method to scroll to position for a specific item (by index or key)

### ISSUE THREAD

**Issue by Tmodurr** [rocwang/vue-virtual-scroll-grid#53]
Create method to scrollTo specific itembased on an index or key in a virtualized list.

**Comment by rocwang** [comment]
It is reasonable feature. I will let you know once I implement it.

**Comment by Tmodurr** [comment]
> It is reasonable feature. I will let you know once I implement it.

Any idea when this might be complete? Thank you for this library!

**Comment by rocwang** [comment]
Unfortunately, I can't give you a concrete timeframe. I'm pretty busy with work at the moment. I will try to slot it in when I get some free time.

**Comment by rocwang** [comment]
Sorted. [Demo is available.](https://grid.kiwiberry.nz/)

**Comment by Tmodurr** [comment]
Thanks @rocwang 🥇
