### ISSUE TITLE
Is there any typescript support

### ISSUE THREAD

**Issue by Erbolking** [rocwang/vue-virtual-scroll-grid#66]
First of all, I'd like to thank you for the great library : )

I'm trying to install it in my project, but got this error:

```
Could not find a declaration file for module 'vue-virtual-scroll-grid'. 'node_modules/vue-virtual-scroll-grid/dist/vue-virtual-scroll-grid.umd.js' implicitly has an 'any' type.
  Try `npm install @types/vue-virtual-scroll-grid` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-virtual-scroll-grid';`
```

Do we have any typings for this library?

Thanks.

**Comment by rocwang** [comment]
Thanks for trying out this library.

There you go. It does provide `.d.ts` files now since `v1.2.0`. Thanks to https://github.com/alloc/vite-dts
